name: Build transGUI exe

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Add FPC to PATH
      run: echo \"C:\\Program Files\\Lazarus\" >> $env:GITHUB_PATH

    - name: Install lazarus
      run: |
        choco install lazarus -y

    - name: Compile transGUI
      run: |
        lazbuild main.pas

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: transgui-binary
        path: ./transgui.exe
